name: Checks

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    tests:
        name: tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: yarn --frozen-lockfile
            - run: yarn test

    type-tests:
        name: type-tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: yarn --frozen-lockfile
            - run: yarn typetest

    lint:
        name: lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: yarn --frozen-lockfile
            - run: yarn lint:eslint

    formatting:
        name: formatting
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: yarn --frozen-lockfile
            - run: yarn lint:prettier

    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: yarn --frozen-lockfile
            - run: yarn build
