name: Coverage

on:
    pull_request:
        branches:
            - main

jobs:
    coverage:
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
        steps:
            - uses: actions/checkout@v1
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  package-manager: yarn
                  annotations: none
