name: Checks

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        name: tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: yarn --frozen-lockfile
            - run: yarn test

    lint:
        name: eslint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: yarn --frozen-lockfile
            - run: yarn lint:eslint

    formatting:
        name: prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: yarn --frozen-lockfile
            - run: yarn lint:prettier

    build:
        name: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'
            - run: yarn --frozen-lockfile
            - run: yarn build
