name: Publish Package

on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag (Optional)'
                required: false

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - run: yarn --frozen-lockfile
            - run: yarn publish --non-interactive ${{ !github.event.inputs.tag && '--tag ' + github.event.inputs.tag || '' }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
